name: Leptos

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Install Trunk
        run: cargo install trunk
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - name: Install nightly
        run: rustup default nightly
      - name: setup webAssembly target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: List folder
        run: trunk build
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: github-pages
      #     path: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write # to deploy to Pages
  #     id-token: write # to verify the deployment originates from an appropriate source
  #
  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy GitHub Pages site
  #       uses: actions/deploy-pages@v1.2.9
