name: Leptos

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Trunk
        run: cargo install trunk
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - name: Install nightly
        run: rustup default nightly
      - name: setup webAssembly target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: List folder
        run: ls -a
      - name: Trunk Build
        run: trunk build
      - name: List folder again
        run: ls -a
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.9
